const fs = require("fs");
const path = require("path");
const readline = require("readline");
const { spawnSync } = require("child_process");
const OpenAI = require("openai");
require("dotenv").config();

/*
|--------------------------------------------------------------------------
| Configuration
|--------------------------------------------------------------------------
*/

const ROOT = process.cwd();

const GYM_DIR = path.join(ROOT, "coding-gym");
const INPUT_FILE = path.join(GYM_DIR, "input.js");
const TEST_FILE = path.join(GYM_DIR, "test.js");
const PROBLEM_FILE = path.join(GYM_DIR, "problem.md");

const TEMP_DIR = path.join(GYM_DIR, ".validation");
const REFERENCE_FILE = path.join(TEMP_DIR, "solution.js");

const HISTORY_DIR = path.join(GYM_DIR, "history");

if (!process.env.OPENAI_API_KEY) {
  throw new Error(
    "OPENAI_API_KEY is not set. Add OPENAI_API_KEY=... to your .env file.",
  );
}
if (!process.env.THEME) {
  throw new Error("THEME is not set. Add THEME=... to your .env file.");
}

const client = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

/*
|--------------------------------------------------------------------------
| CLI helpers
|--------------------------------------------------------------------------
*/

function askQuestion(question) {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      rl.close();
      resolve(answer);
    });
  });
}

async function askDifficulty() {
  console.log("");
  console.log("Choose a difficulty:");
  console.log("");
  console.log("  1. Easy");
  console.log("  2. Medium");
  console.log("  3. Hard");
  console.log("");

  while (true) {
    const answer = await askQuestion("> ");

    switch (answer.trim().toLowerCase()) {
      case "1":
      case "easy":
        return "easy";

      case "2":
      case "medium":
        return "medium";

      case "3":
      case "hard":
        return "hard";

      default:
        console.log("Please choose 1, 2, or 3.");
    }
  }
}

async function askHints() {
  console.log("");
  console.log("Generate hints?");
  console.log("");
  console.log("  y. Yes");
  console.log("  n. No");
  console.log("");

  while (true) {
    const answer = await askQuestion("> ");

    switch (answer.trim().toLowerCase()) {
      case "y":
      case "yes":
        return true;

      case "n":
      case "no":
        return false;

      default:
        console.log("Please enter y or n.");
    }
  }
}

function hasFlag(name) {
  return process.argv.includes(name);
}

function printUsage() {
  console.log(`
Coding Gym

Generate a new problem:

  npm run gym
  npm run gym -- --hints

Run the current tests:

  npm run gym:test

Work on the current problem interactively:

  npm run gym:solve

Show the current problem:

  npm run gym:show

Direct commands:

  node scripts/generate.js generate
  node scripts/generate.js generate --hints
  node scripts/generate.js test
  node scripts/generate.js solve
  node scripts/generate.js show

Files:

  coding-gym/
    input.js
    test.js
    problem.md
    history/
      YYYY-MM-DD.json

The test.js file is generated by the AI and should never be modified
by the user.
`);
}

/*
|--------------------------------------------------------------------------
| Files / directories
|--------------------------------------------------------------------------
*/

function ensureDirectories() {
  fs.mkdirSync(GYM_DIR, { recursive: true });
  fs.mkdirSync(HISTORY_DIR, { recursive: true });
}

function removeFile(filePath) {
  if (fs.existsSync(filePath)) {
    fs.unlinkSync(filePath);
  }
}

function removeValidationDirectory() {
  if (fs.existsSync(TEMP_DIR)) {
    fs.rmSync(TEMP_DIR, {
      recursive: true,
      force: true,
    });
  }
}

/*
|--------------------------------------------------------------------------
| Dates / history
|--------------------------------------------------------------------------
*/

function getToday() {
  const now = new Date();

  const year = now.getFullYear();
  const month = String(now.getMonth() + 1).padStart(2, "0");
  const day = String(now.getDate()).padStart(2, "0");

  return `${year}-${month}-${day}`;
}

function getHistoryPath() {
  return path.join(HISTORY_DIR, `${getToday()}.json`);
}

function readJson(filePath, fallback) {
  if (!fs.existsSync(filePath)) {
    return fallback;
  }

  try {
    return JSON.parse(fs.readFileSync(filePath, "utf8"));
  } catch (error) {
    throw new Error(`Could not parse JSON file: ${filePath}\n${error.message}`);
  }
}

function writeJson(filePath, value) {
  fs.writeFileSync(filePath, JSON.stringify(value, null, 2) + "\n", "utf8");
}

function createEmptyHistory() {
  return {
    date: getToday(),
    problems: [],
  };
}

function loadTodayHistory() {
  ensureDirectories();

  const historyPath = getHistoryPath();

  if (!fs.existsSync(historyPath)) {
    const history = createEmptyHistory();

    writeJson(historyPath, history);

    return history;
  }

  return readJson(historyPath, createEmptyHistory());
}

function saveTodayHistory(history) {
  ensureDirectories();

  writeJson(getHistoryPath(), history);
}

/*
|--------------------------------------------------------------------------
| AI response parsing
|--------------------------------------------------------------------------
*/

function cleanGeneratedText(text) {
  if (!text) {
    return "";
  }

  return text
    .replace(/^```json\s*/i, "")
    .replace(/^```\s*/i, "")
    .replace(/\s*```$/i, "")
    .trim();
}

function extractJson(text) {
  const cleaned = cleanGeneratedText(text);

  try {
    return JSON.parse(cleaned);
  } catch (_) {
    const start = cleaned.indexOf("{");
    const end = cleaned.lastIndexOf("}");

    if (start === -1 || end === -1 || end <= start) {
      throw new Error("AI response did not contain valid JSON.");
    }

    try {
      return JSON.parse(cleaned.slice(start, end + 1));
    } catch (error) {
      throw new Error(`Could not parse AI-generated JSON: ${error.message}`);
    }
  }
}

/*
|--------------------------------------------------------------------------
| Problem validation
|--------------------------------------------------------------------------
*/

function validateGeneratedProblem(problem) {
  const requiredFields = ["problem", "input", "test", "solution"];

  for (const field of requiredFields) {
    if (typeof problem[field] !== "string" || !problem[field].trim()) {
      throw new Error(`AI response is missing required field: ${field}`);
    }
  }

  if (!problem.problemId) {
    problem.problemId = `problem-${Date.now()}`;
  }

  if (!problem.title) {
    problem.title = "Coding Exercise";
  }

  if (!problem.difficulty) {
    problem.difficulty = "unknown";
  }

  return problem;
}

function validateJavaScript(contents, filename) {
  const result = spawnSync(process.execPath, ["--check"], {
    input: contents,
    encoding: "utf8",
  });

  if (result.status !== 0) {
    throw new Error(
      `AI generated invalid JavaScript for ${filename}:\n\n${
        result.stderr || result.stdout || "Unknown syntax error."
      }`,
    );
  }
}

/*
|--------------------------------------------------------------------------
| Generated problem validation
|--------------------------------------------------------------------------
*/

function prepareValidationFiles(problem) {
  removeValidationDirectory();

  fs.mkdirSync(TEMP_DIR, {
    recursive: true,
  });

  /*
   * We copy the user's starter code into the normal
   * input.js location temporarily.
   */
  fs.writeFileSync(INPUT_FILE, problem.input.trim() + "\n", "utf8");

  fs.writeFileSync(TEST_FILE, problem.test.trim() + "\n", "utf8");

  /*
   * The reference solution is temporary.
   *
   * It will NEVER be left in the final coding-gym
   * directory.
   */
  fs.writeFileSync(REFERENCE_FILE, problem.solution.trim() + "\n", "utf8");
}

function runNodeTests(testFile) {
  const result = spawnSync(process.execPath, ["--test", testFile], {
    cwd: ROOT,
    encoding: "utf8",
  });

  return {
    passed: result.status === 0,
    status: result.status,
    output: [result.stdout || "", result.stderr || ""].join("\n"),
  };
}

function buildReferenceTestFile(problem) {
  /*
   * Replace "./input" in the generated test with
   * the temporary reference solution.
   *
   * This allows us to test the AI's reference answer
   * without changing the user's actual test.js.
   */
  return problem.test.replace(
    /require\(\s*['"]\.\/input['"]\s*\)/g,
    `require(${JSON.stringify(REFERENCE_FILE)})`,
  );
}

function validateReferenceSolution(problem) {
  const referenceTestFile = path.join(TEMP_DIR, "reference-test.js");

  const referenceTests = buildReferenceTestFile(problem);

  fs.writeFileSync(referenceTestFile, referenceTests, "utf8");

  const result = runNodeTests(referenceTestFile);

  if (!result.passed) {
    return {
      valid: false,
      output: result.output,
    };
  }

  return {
    valid: true,
    output: result.output,
  };
}

function validateStarterSolution() {
  const result = runNodeTests(TEST_FILE);

  /*
   * We WANT the starter solution to fail.
   *
   * If it passes all tests immediately, there is
   * nothing for the user to solve.
   */
  if (result.passed) {
    return {
      valid: false,
      output:
        "The starter input.js passed every test. " +
        "The generated exercise does not provide a challenge.",
    };
  }

  /*
   * A non-zero exit is expected, but we want to
   * make sure the failure is actually an assertion
   * failure rather than a broken test file.
   */
  const brokenPatterns = [
    /SyntaxError/i,
    /MODULE_NOT_FOUND/i,
    /Cannot find module/i,
    /ERR_MODULE_NOT_FOUND/i,
    /ReferenceError/i,
    /TypeError.*is not a function/i,
  ];

  const isBroken = brokenPatterns.some((pattern) =>
    pattern.test(result.output),
  );

  if (isBroken) {
    return {
      valid: false,
      output: result.output,
    };
  }

  return {
    valid: true,
    output: result.output,
  };
}

function validateGeneratedProblemCompletely(problem) {
  console.log("");
  console.log("Validating generated exercise...");

  /*
   * First validate all generated JavaScript syntax.
   */
  validateJavaScript(problem.input, "input.js");

  validateJavaScript(problem.test, "test.js");

  validateJavaScript(problem.solution, "reference solution");

  /*
   * Prepare temporary files.
   */
  prepareValidationFiles(problem);

  /*
   * The reference implementation MUST pass.
   */
  console.log("  Checking reference solution...");

  const reference = validateReferenceSolution(problem);

  if (!reference.valid) {
    return {
      valid: false,
      reason: "The reference solution does not pass its own tests.",
      output: reference.output,
    };
  }

  console.log("  ✓ Reference solution passes all tests.");

  /*
   * The starter implementation MUST fail.
   */
  console.log("  Checking starter solution...");

  const starter = validateStarterSolution();

  if (!starter.valid) {
    return {
      valid: false,
      reason: "The starter solution does not behave as expected.",
      output: starter.output,
    };
  }

  console.log("  ✓ Starter solution fails as expected.");

  return {
    valid: true,
    output: "",
  };
}

/*
|--------------------------------------------------------------------------
| Writing the actual problem
|--------------------------------------------------------------------------
*/

function writeGeneratedFiles(problem) {
  ensureDirectories();

  fs.writeFileSync(PROBLEM_FILE, problem.problem.trim() + "\n", "utf8");

  fs.writeFileSync(INPUT_FILE, problem.input.trim() + "\n", "utf8");

  fs.writeFileSync(TEST_FILE, problem.test.trim() + "\n", "utf8");
}

/*
|--------------------------------------------------------------------------
| Cleanup
|--------------------------------------------------------------------------
*/

function cleanupAfterGeneration() {
  removeValidationDirectory();
}

/*
|--------------------------------------------------------------------------
| Package.json
|--------------------------------------------------------------------------
*/

function updatePackageJson() {
  const packagePath = path.join(ROOT, "package.json");

  if (!fs.existsSync(packagePath)) {
    return;
  }

  const packageJson = readJson(packagePath, {});

  packageJson.scripts = packageJson.scripts || {};

  const scriptPath = path.relative(
    ROOT,
    path.join(ROOT, "scripts", path.basename(__filename)),
  );

  const normalizedScriptPath = scriptPath.split(path.sep).join("/");

  packageJson.scripts.gym = `node ${normalizedScriptPath}`;

  packageJson.scripts["gym:test"] = `node ${normalizedScriptPath} test`;

  packageJson.scripts["gym:solve"] = `node ${normalizedScriptPath} solve`;

  packageJson.scripts["gym:show"] = `node ${normalizedScriptPath} show`;

  fs.writeFileSync(
    packagePath,
    JSON.stringify(packageJson, null, 2) + "\n",
    "utf8",
  );
}

/*
|--------------------------------------------------------------------------
| AI prompt
|--------------------------------------------------------------------------
*/

function buildGenerationPrompt({ hints, previousHistory, difficulty }) {
  const difficultyExplanation = difficulty
    ? `The difficulty level is "${difficulty}".`
    : "The difficulty level is not specified.";

  const difficultyDefinitions = {
    easy: "Easy problems should be solvable in 10-15 minutes by a beginner to intermediate JavaScript developer. They should focus on basic programming concepts, data structures, and algorithms without requiring advanced knowledge or complex logic.",
    medium:
      "Medium problems should be solvable in 15-30 minutes by an intermediate JavaScript developer. They may involve more complex logic, multiple steps, and a deeper understanding of JavaScript features and data structures.",
    hard: "Hard problems should be solvable in 30-60 minutes by an experienced JavaScript developer. They may involve advanced algorithms, optimization, and require a strong understanding of JavaScript and programming concepts.",
  };
  const historyText =
    previousHistory.length > 0
      ? JSON.stringify(previousHistory, null, 2)
      : "No previous problems are available.";

  return `
You are designing a coding exercise for a local
JavaScript coding gym.

Your job is to create ONE small, realistic,
solvable programming problem.

The user will receive:

- problem.md
- input.js
- test.js

The user will ONLY modify input.js.

The user must NEVER need to modify test.js.

You must ALSO generate a reference solution.
The reference solution will be used internally to
verify that your tests are actually solvable.

The reference solution will NOT be shown to the user.

==================================================
CRITICAL VALIDITY REQUIREMENTS
==================================================

The problem and tests MUST be internally consistent.

The reference solution MUST pass every test.

The starter input.js MUST fail at least one test.

Every test must represent behavior described by
problem.md.

Do NOT create impossible tests.

Do NOT require a specific implementation technique.

For example, if a problem can be solved with a loop,
Map, Set, recursion, or another valid technique,
the tests must only verify the result.

All tests must be deterministic.

Do not use:

- network requests
- environment variables
- random values
- current time
- user input
- external services
- external npm packages
- filesystem state outside the exercise

==================================================
JAVASCRIPT CONTRACT
==================================================

input.js MUST export:

module.exports = { solve };

The function should look like:

function solve(input) {
  // starter implementation
}

module.exports = { solve };

The reference solution MUST export the same function:

function solve(input) {
  // complete correct implementation
}

module.exports = { solve };

test.js MUST use Node's built-in test framework:

const test = require('node:test');
const assert = require('node:assert/strict');

const { solve } = require('./input');

Tests should use test() and assertions.

==================================================
PROBLEM SIZE
==================================================

The problem should generally take:

5 minutes to understand
10-30 minutes to solve

It should be useful for practicing real
JavaScript programming.

Avoid:

- huge algorithms
- obscure mathematical tricks
- LeetCode-style trick questions
- problems requiring knowledge not explained
- ambiguous requirements
- excessive boilerplate

==================================================
PROBLEM.MD
==================================================

The problem description must clearly explain:

- the goal
- the input
- the output
- rules
- constraints
- examples
- edge cases

The examples must be correct.

==================================================
INPUT.JS
==================================================

input.js is the user's working file.

It may contain:

- a function stub
- starter code
- variables
- partial implementation
- comments

It MUST export solve.

${
  hints
    ? `
HINT MODE IS ENABLED.

Include useful inline hints in input.js.

Hints should guide the user without giving away
the complete implementation.

Examples:

// Hint: Think about using a Set here.

// Hint: What should happen when the array is empty?

// Hint: Consider whether the order of the values matters.

Do NOT include the complete solution in the hints.
`
    : `
HINT MODE IS DISABLED.

Do not include solution hints in input.js.
`
}

${
  difficulty
    ? `the user has specified a difficulty level for this problem.
DIFFICULTY: ${difficulty.toUpperCase()}  explanation: ${difficultyDefinitions[difficulty] || "No explanation available."}`
    : ""
}

==================================================
TEST.JS
==================================================

Generate several meaningful tests.

Include:

- normal cases
- edge cases
- boundary cases where appropriate

Tests must check exact expected behavior.

The tests must be independent.

The tests must pass against the reference solution.

The tests must fail against the starter solution.

==================================================
REFERENCE SOLUTION
==================================================

Generate a complete correct solution.

The reference solution is ONLY used internally
to verify the problem.

It must follow the exact requirements in problem.md.

Do not cheat by modifying tests.

==================================================
PREVIOUS HISTORY
==================================================

Use the previous history to avoid repeatedly
generating the exact same type of exercise.

Do not make the new problem dependent on previous
problems.

Previous history:

${historyText}

==================================================
OUTPUT
==================================================

Return ONLY valid JSON.

The JSON must contain exactly these fields:

{
  "problemId": "unique-short-id",
  "title": "short title",
  "difficulty": "easy|medium|hard",
  "problem": "complete Markdown for problem.md",
  "input": "complete JavaScript for input.js",
  "test": "complete JavaScript for test.js",
  "solution": "complete JavaScript reference solution"
}

Do not use Markdown fences around the JSON.

${
  process.env.THEME
    ? `
==================================================
THEME: ${process.env.THEME}
==================================================

for a bit of fun the user has requested that the problem be themed around ${process.env.THEME}. please make sure the word problem associated with the code is themed around this topic`
    : ""
}
`.trim();
}

/*
|--------------------------------------------------------------------------
| Generate problem
|--------------------------------------------------------------------------
*/

async function generateProblem(hints, difficulty) {
  ensureDirectories();

  const history = loadTodayHistory();
  console.log("");
  console.log("Generating a new coding exercise...");

  console.log(hints ? "Hints: enabled" : "Hints: disabled");

  const response = await client.responses.create({
    model: "gpt-5.6-luna",
    input: [
      {
        role: "user",
        content: [
          {
            type: "input_text",
            text: buildGenerationPrompt({
              hints,
              difficulty,
              previousHistory: history.problems.slice(-10),
            }),
          },
        ],
      },
    ],
  });

  const generated = validateGeneratedProblem(extractJson(response.output_text));

  const validation = validateGeneratedProblemCompletely(generated);

  if (!validation.valid) {
    cleanupAfterGeneration();

    throw new Error(
      [
        "AI generated an invalid exercise.",
        "",
        validation.reason,
        "",
        validation.output,
      ].join("\n"),
    );
  }

  /*
   * At this point the problem has passed validation.
   *
   * Now write the user-facing files.
   */
  writeGeneratedFiles(generated);

  cleanupAfterGeneration();

  updatePackageJson();

  /*
   * Record the problem.
   */
  const newHistory = loadTodayHistory();

  newHistory.problems.push({
    id: generated.problemId,
    title: generated.title,
    difficulty: generated.difficulty,
    explanation: generated.problem,
    attempts: 0,
    succeeded: false,
    generatedAt: new Date().toISOString(),
  });

  saveTodayHistory(newHistory);

  console.log("");
  console.log("================================");
  console.log("   Coding exercise generated!");
  console.log("================================");
  console.log("");
  console.log(`Title:      ${generated.title}`);
  console.log(`Difficulty: ${generated.difficulty}`);
  console.log("");
  console.log("Files created:");
  console.log(`  ${PROBLEM_FILE}`);
  console.log(`  ${INPUT_FILE}`);
  console.log(`  ${TEST_FILE}`);
  console.log("");
  console.log("Start solving with:");
  console.log("  npm run gym:solve");
  console.log("");
}

/*
|--------------------------------------------------------------------------
| Current problem
|--------------------------------------------------------------------------
*/

function currentProblemExists() {
  return (
    fs.existsSync(PROBLEM_FILE) &&
    fs.existsSync(INPUT_FILE) &&
    fs.existsSync(TEST_FILE)
  );
}

function getCurrentProblem() {
  if (!currentProblemExists()) {
    return null;
  }

  return {
    problem: fs.readFileSync(PROBLEM_FILE, "utf8").trim(),

    input: fs.readFileSync(INPUT_FILE, "utf8"),

    test: fs.readFileSync(TEST_FILE, "utf8"),
  };
}

/*
|--------------------------------------------------------------------------
| Running tests
|--------------------------------------------------------------------------
*/

function runCurrentTests() {
  if (!currentProblemExists()) {
    console.error("No coding problem exists yet.");

    console.error('Run "npm run gym" first.');

    return false;
  }

  console.log("");
  console.log("Running coding-gym tests...");
  console.log("");

  const result = runNodeTests(TEST_FILE);

  process.stdout.write(result.output);

  const succeeded = result.passed;

  updateCurrentProblemHistory({
    succeeded,
  });

  return succeeded;
}

/*
|--------------------------------------------------------------------------
| History tracking
|--------------------------------------------------------------------------
*/

function getLatestProblemHistory() {
  const history = loadTodayHistory();

  if (!history.problems || history.problems.length === 0) {
    return null;
  }

  return history.problems[history.problems.length - 1];
}

function updateCurrentProblemHistory({ succeeded }) {
  const history = loadTodayHistory();

  if (!history.problems || history.problems.length === 0) {
    return;
  }

  // The last problem in today's history is the
  // problem currently being worked on.
  const currentProblem = history.problems[history.problems.length - 1];

  if (!currentProblem) {
    return;
  }

  currentProblem.attempts = Number(currentProblem.attempts || 0) + 1;

  if (succeeded) {
    currentProblem.succeeded = true;

    if (!currentProblem.completedAt) {
      currentProblem.completedAt = new Date().toISOString();
    }
  }

  saveTodayHistory(history);
}

/*
|--------------------------------------------------------------------------
| Solve mode
|--------------------------------------------------------------------------
*/

async function solveMode() {
  if (!currentProblemExists()) {
    console.error("No coding problem exists yet.");

    console.error('Run "npm run gym" first.');

    return;
  }

  console.log("");
  console.log("================================");
  console.log("          Coding Gym");
  console.log("================================");
  console.log("");

  console.log(`Problem: ${PROBLEM_FILE}`);

  console.log(`Input:   ${INPUT_FILE}`);

  console.log(`Tests:   ${TEST_FILE}`);

  console.log("");

  console.log("Edit input.js, then press Enter");

  console.log("to run the tests.");

  console.log('Type "quit" to exit.');

  console.log("type 'HELP' for hints.");

  console.log("");

  while (true) {
    const answer = await askQuestion("> ");

    if (answer.trim().toLowerCase() === "quit") {
      break;
    }

    if (answer.trim().toLowerCase() === "help") {
      const currentProblem = getCurrentProblem();

      if (!currentProblem) {
        console.error("No coding problem exists yet.");

        console.error('Run "npm run gym" first.');

        return;
      }

      const hints = await client.responses.create({
        model: "gpt-5.6-luna",
        input: [
          {
            role: "user",
            content: [
              {
                type: "input_text",
                text: `The user is working on a coding exercise. The user has the following input.js:\n\n${currentProblem.input}\n\nThe user has the following test.js:\n\n${currentProblem.test}\n\nPlease provide 1 to 3 hints to help the user solve the problem. The hints should be concise and helpful, but not give away the complete solution. The hints should be in plain text format.`,
              },
            ],
          },
        ],
      });

      console.log(currentProblem.input);

      console.log("");
      console.log("Hints:");
      console.log(hints.output_text);
      console.log("");

      continue;
    }

    const succeeded = runCurrentTests();

    console.log("");

    if (succeeded) {
      console.log("🎉 Problem solved!");

      console.log("");
      console.log("Your result has been recorded");
      console.log("in today's history file.");

      break;
    }

    console.log("Keep working on input.js.");

    console.log("Press Enter to test again.");

    console.log("");
  }
}

/*
|--------------------------------------------------------------------------
| Show problem
|--------------------------------------------------------------------------
*/

function showProblem() {
  if (!fs.existsSync(PROBLEM_FILE)) {
    console.log("No problem has been generated yet.");

    return;
  }

  console.log("");
  console.log(fs.readFileSync(PROBLEM_FILE, "utf8"));
  console.log("");
}

/*
|--------------------------------------------------------------------------
| Main
|--------------------------------------------------------------------------
*/

async function main() {
  const command = process.argv[2];

  if (command === "help" || command === "--help" || command === "-h") {
    printUsage();
    return;
  }

  if (command === "test" || command === "--test") {
    runCurrentTests();
    return;
  }

  if (command === "solve" || command === "--solve") {
    await solveMode();
    return;
  }

  if (command === "show") {
    showProblem();
    return;
  }

  const hints = hasFlag("--hints");

  if (
    command === undefined ||
    command === "generate" ||
    command === "--generate" ||
    command === "--hints"
  ) {
    let difficulty = null;
    let hints = hasFlag("--hints");

    if (!hasFlag("--no-prompt")) {
      difficulty = await askDifficulty();
      hints = await askHints();
    }

    await generateProblem(hints, difficulty);

    return;
  }

  printUsage();
}

main().catch((error) => {
  console.error("");
  console.error("Coding Gym Error:");
  console.error("");
  console.error(error.message);

  process.exitCode = 1;
});
